---
title: "Presenting the dataset"
author: "Marc Comas-Cufí,  Antonella Buccianti, Josep Antoni Martín-Fernández and Glòria Mateu-Figueras"
date: "July 14, 2015"
output: 
  html_document: 
    toc: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, echo=FALSE, comment="   ")
options(width=200)
library(ggmap)
library(ggplot2)
library(tidyr)
library(dplyr)
library(mixpack)
library(gridExtra)
source('R/plot_functions.R')
load('data/iamg_data.RData')
load('data/iamg_map.RData')
compo = function(.data) .data %>% select(HCO3, Ca, Cl, Mg, K, Na, SO4) %>% subset(apply(., 1, prod) != 0)
closure = function(.data, k = 100) (k*.data/apply(.data, 1, sum)) %>% round(4) %>% tbl_df

gmean = function(...){
  .data = data.frame(list(...))
  apply(.data, 1, prod)^(1/NCOL(.data))
}
balance = function(.data) .data %>% select(HCO3, Ca, Cl, Mg, K, Na, SO4) %>%
  mutate(
    b1 = sqrt(4*3/(4+3)) * log(gmean(Ca, Mg, Na, K) / gmean(HCO3, SO4, Cl)),
    b2 = sqrt(2*2/(2+2)) * log(gmean(Ca, Mg) / gmean(Na, K)),
    b3 = sqrt(1*1/(1+1)) * log(Ca/Mg),
    b4 = sqrt(1*1/(1+1)) * log(Na/K),
    b5 = sqrt(1*2/(1+2)) * log(gmean(HCO3)/gmean(SO4, Cl)),
    b6 = sqrt(1*1/(1+1)) * log(SO4/Cl) ) %>% select(b1,b2,b3,b4,b5,b6)

```

`r nrow(data)` observations were collected in Tuscany region (central Italy).

```{r, fig.width=4, fig.height=4}
ggmap(map) + 
  geom_point(data = data, aes(x = lon, y = lat), alpha=0.4) +
  xlab(NULL) + ylab(NULL) +
  theme(axis.ticks = element_blank(), axis.text = element_blank())
```

Some observations were collected at the same point.

```{r, include=F}
data %>% group_by(est, nord) %>% 
  summarise(rep = length(ph)) %>% group_by(rep) %>% 
  summarise(freq = length(rep))
```

# Numeric descriptives

## Component distribution

* Raw data

```{r}
data %>% compo %>% gather(key=component, value=val) %>% 
  group_by(component) %>%
  summarise(
    min = min(val, na.rm=T),
    q1 = quantile(val, 0.25, na.rm=T),
    median = median(val, na.rm=T),
    q3 = quantile(val, 0.75, na.rm=T),
    max = max(val, na.rm=T) )
```

* Closured data (100%)

```{r}
data %>% compo %>% closure %>% gather(key=component, value=val) %>% 
  group_by(component) %>%
  summarise(
    min = min(val, na.rm=T),
    q1 = quantile(val, 0.25, na.rm=T),
    median = median(val, na.rm=T),
    q3 = quantile(val, 0.75, na.rm=T),
    max = max(val, na.rm=T) )
```

## Variation array

```{r}
variation_array = function(.data){
  vrs = names(.data)
  reshape2::melt(.data, id.vars = vrs, measure.vars = vrs, 
       value.name = 'val.row', variable.name = 'var.array') %>%
  reshape2::melt(id.vars = c(vrs, 'var.array', 'val.row'), measure.vars = vrs, 
       value.name = 'val.col', variable.name = 'var.col') %>% 
  group_by(var.array, var.col) %>% summarize(
  'm' = mean(log(val.row/val.col)),
  'v' = var(log(val.row/val.col)),
  'l' = sprintf("  %3.1f (%3.1f)", m, v)) %>% reshape2::dcast(var.array~var.col, value.var = 'l')
}
data %>% compo %>% variation_array
```

# Graphic descriptives

## CLR-biplot

```{r, fig.width=9, fig.height=7}
alpha = .25
Xclr = clr_coordinates(X = data %>% compo) %>% tbl_df
labels = sprintf("clr(%s)", names(Xclr))

grid.arrange(
  ggplot_biplot(X = Xclr, labels = labels, x = 1, y = 2, alpha=alpha),
  ggplot_biplot(X = Xclr, labels = labels, x = 3, y = 2, alpha=alpha),
  ggplot_biplot(X = Xclr, labels = labels, x = 1, y = 3, alpha=alpha), 
  nrow = 2, ncol = 2, main='CLR-biplot')
```

## Principal balances

```
b1 = sqrt(4*3/(4+3)) * log(gmean(Ca, Mg, Na, K) / gmean(HCO3, SO4, Cl)),
b2 = sqrt(2*2/(2+2)) * log(gmean(Ca, Mg) / gmean(Na, K)),
b3 = sqrt(1*1/(1+1)) * log(Ca/Mg),
b4 = sqrt(1*1/(1+1)) * log(Na/K),
b5 = sqrt(1*2/(1+2)) * log(gmean(HCO3)/gmean(SO4, Cl)),
b6 = sqrt(1*1/(1+1)) * log(SO4/Cl) 
```

```{r, fig.width=9, fig.height=2}
d = data %>% compo %>% balance %>% gather(key=balance, value=val)

ggplot(d) + geom_histogram(aes(x=val, y=..density..), binwidth=0.1) + 
  facet_wrap(~balance, nrow=1) + 
  geom_vline(x=0, col='red') + theme_bw() + ggtitle('Balances')
```

```{r}
cor(data %>% compo %>% balance)
```

```{r, fig.width=9, fig.height=9}
pairs(~b1+b2+b3+b4+b5+b6, data=data %>% balance)
```

```{r, eval=F}
hc = hclust(data %>% select(lon, lat) %>% na.omit %>% dist)
```

