````{r, include=FALSE}
if(!exists('ROOT')) ROOT = getwd()
load(sprintf('%s/data/data_with_selected_variables_and_map.RData', ROOT))
library(stringr)
options(width=100)
```

Cleaning the dataset
====================

#### Some facies are not well coded

* Before:

```{r, comment=""}
table(data$Facies)
```

* Now:

```{r, comment=""}
data$Facies[str_sub(data$Facies, 1, 6) == 'Ca-HCO'] = 'Ca-HCO3'
data$Facies = as.character(data$Facies)
table(data$Facies)
```

#### Facies are rebuild from percentage

```{r}
facie_1 <- c('Ca', 'Mg', 'Na')
facie_2 <- c('SO4', 'HCO3', 'Cl')

facie.c = apply(data[,facie_1], 1, function(r) facie_1[which.max(r)]) 
facie.a = apply(data[,facie_2], 1, function(r) facie_2[which.max(r)])

data$Facies2 = sprintf("%s-%s", facie.c, facie.a)
```

There are facies which are not as they are supposed to be. 

```{r, comment=""}
mean(data$Facies != data$Facies2)
```

They are distributed as follows:

```{r, comment=""}
table('Facies' = data$Facies, 'Facies2' = data$Facies2)
```

* The disagreement is minimum, maybe a manual error when coding Facies? 
* Maybe, the percentages from where Facies2 was calculated were not correct?

```{r, include=FALSE}
save(map, data, file=sprintf('%s/data/clean_data.RData', ROOT))
```