```{r, include=FALSE}
library(ggplot2)
library(ggmap)
library(grid)
library(dplyr)
library(reshape2)
library(ggtern)
library(stringr)
library(mixpack)
library(flexmix)
library(gridExtra)
if(!exists('ROOT')) ROOT = getwd()
load(sprintf('%s/data/clean_data.RData', ROOT))

##############
### Preparing data
df1.coda = data %>% 
  mutate(
    'Facie' = factor(sapply(str_split(data$Facies, '-'), function(v) v[1]), levels=c('Ca', 'Mg', 'Na'))
    ) %>%
  select(x, y, Facie, Ca, Mg, Na)

df2.coda <- data %>%
  mutate(
    'Facie' = factor(sapply(str_split(data$Facies, '-'), function(v) v[2]), levels=c('SO4', 'HCO3', 'Cl'))
    ) %>% 
  select(x, y, Facie, SO4, HCO3, Cl)

df1.clr = df1.coda %>% 
  mutate(
    'clrCa' = log(Ca/(Ca*Mg*Na)^(1/3)),
    'clrMg' = log(Mg/(Ca*Mg*Na)^(1/3)),
    'clrNa' = log(Na/(Ca*Mg*Na)^(1/3))
    ) %>% 
  select(x, y, Facie, clrCa, clrMg, clrNa)
df2.clr = df2.coda %>% 
  mutate(
    'clrSO4'  = log(SO4/(SO4*HCO3*Cl)^(1/3)),
    'clrHCO3' = log(HCO3/(SO4*HCO3*Cl)^(1/3)),
    'clrCl'   = log(Cl/(SO4*HCO3*Cl)^(1/3))
    ) %>% 
  select(x, y, Facie, clrSO4, clrHCO3, clrCl)

df1.ilr = ilr_coordinates(df1.coda %>% select(Ca, Mg, Na) )  %>% cbind(df1.coda %>% select(Facie))
df2.ilr = ilr_coordinates(df2.coda %>% select(SO4, HCO3, Cl))  %>% cbind(df2.coda %>% select(Facie))

save(df1.coda, df2.coda, df1.clr, df2.clr, df1.ilr, df2.ilr, file=sprintf('%s/data/data-trans.RData', ROOT))
```


Descriptives
============

* [Facies on the map](#facies_map)
* [Facies on a ternary diagram](#coda_tern)
* [Variation array](#variation_array)
* [ILR-plot](#ilr_plot)

### <a name="facies_map"> Facies on the map

```{r, fig.width=10, fig.height=5, warning=FALSE, echo=FALSE, comment=""}
df = bind_rows(
  df1.coda %>% melt(id.vars = c('x', 'y', 'Facie')) %>% mutate(compo = 'Ca-Mg-Na') %>% select(x,y,Facie,compo),
  df2.coda %>% melt(id.vars = c('x', 'y', 'Facie')) %>% mutate(compo = 'SO4-HCO3-Cl') %>% select(x,y,Facie,compo))

grid.arrange(
  ggmap(map) + 
    geom_point(data = df1.coda %>% melt(id.vars = c('x', 'y', 'Facie')), 
               aes(x = x, y = y, col=Facie), size=3,  alpha = .5) +
    xlab(NULL) + ylab(NULL) +
    theme(axis.ticks = element_blank(), axis.text = element_blank()),
  ggmap(map) + 
    geom_point(data = df2.coda %>% melt(id.vars = c('x', 'y', 'Facie')), 
              aes(x = x, y = y, col=Facie), size=3,  alpha = .5) +
    xlab(NULL) + ylab(NULL) +
    theme(axis.ticks = element_blank(), axis.text = element_blank()), ncol=2)
```

### <a name="coda_tern"> Facies on a ternary diagram

#### (Ca,Mg,Na)-composition

```{r, fig.width=6, fig.height=5, echo=FALSE}
df1.coda$Facie2 = df2.coda$Facie

ggtern(data = df1.coda, aes(x=Ca, Mg, Na)) + 
  geom_point(aes(col=Facie2), alpha=0.25) + geom_density2d() + theme_classic()
```

#### (SO4,HCO3,Cl)-composition

```{r, fig.width=6, fig.height=5, echo=FALSE}
df2.coda$Facie2 = df1.coda$Facie
ggtern(data = df2.coda, aes(x=SO4, HCO3, Cl)) + 
  geom_point(aes(col=Facie2), alpha=0.25) + geom_density2d() + theme_classic()
```

### <a name="variation_array"> Variation array

#### (Ca,Mg,Na)-composition

```{r, echo=FALSE, comment=""}
df1.coda %>% select(Ca, Mg, Na) %>% 
  melt(id.vars = c('Ca', 'Mg', 'Na'), measure.vars = c('Ca', 'Mg', 'Na'), 
       value.name = 'val.row', variable.name = 'var.row') %>%
  melt(id.vars = c('Ca', 'Mg', 'Na', 'var.row', 'val.row'), measure.vars = c('Ca', 'Mg', 'Na'), 
       value.name = 'val.col', variable.name = 'var.col') %>% 
  group_by(var.row, var.col) %>% summarize(
  'm' = mean(log(val.row/val.col)),
  'v' = var(log(val.row/val.col)),
  'l' = sprintf("  %5.3f (%5.3f)", m, v)) %>% dcast(var.row~var.col, value.var = 'l')
```

#### (SO4,HCO3,Cl)-composition

```{r, echo=FALSE, comment=""}
df2.coda %>% select(SO4, HCO3, Cl) %>% 
  melt(id.vars = c('SO4', 'HCO3', 'Cl'), measure.vars = c('SO4', 'HCO3', 'Cl'), 
       value.name = 'val.row', variable.name = 'var.row') %>%
  melt(id.vars = c('SO4', 'HCO3', 'Cl', 'var.row', 'val.row'), measure.vars = c('SO4', 'HCO3', 'Cl'), 
       value.name = 'val.col', variable.name = 'var.col') %>% 
  group_by(var.row, var.col) %>% summarize(
  'm' = mean(log(val.row/val.col)),
  'v' = var(log(val.row/val.col)),
  'l' = sprintf("  %5.3f (%5.3f)", m, v)) %>% dcast(var.row~var.col, value.var = 'l')
```

### <a name="ilr_plot"> ILR-plot

Basis:

```{r, echo=FALSE, comment=""}
ilr_basis(D=3)
```

```{r, fig.width=12, fig.height=10, echo=FALSE, comment=""}
df1.ilr$Facie2 = df2.ilr$Facie
df2.ilr$Facie2 = df1.ilr$Facie
grid.arrange(
  ggplot( data = df1.ilr ) +
    geom_point(aes(x=coord.1, y=coord.2, col=Facie), alpha=0.5) + 
    geom_density2d(aes(x=coord.1, y=coord.2)) + theme_classic(),
  ggplot( data = df1.ilr ) +
    geom_point(aes(x=coord.1, y=coord.2, col=Facie2), alpha=0.5) + 
    geom_density2d(aes(x=coord.1, y=coord.2)) + theme_classic(),
  ggplot( data = df2.ilr ) +
    geom_point(aes(x=coord.1, y=coord.2, col=Facie), alpha=0.5) + 
    geom_density2d(aes(x=coord.1, y=coord.2)) + theme_classic(),
  ggplot( data = df2.ilr ) +
    geom_point(aes(x=coord.1, y=coord.2, col=Facie2), alpha=0.5) + 
    geom_density2d(aes(x=coord.1, y=coord.2)) + theme_classic(), ncol=2 , nrow=2)
```